CONFIG+=staticlib
TEMPLATE = lib
TARGET = L
DESTDIR = ../lib 
INCLUDEPATH += . ../include ../../c++adt/include
DEPENDPATH += $$INCLUDEPATH
######################################################################
# Automatically generated by qmake (2.00a) Thu Aug 17 14:56:00 2006
######################################################################





# Input
SOURCES +=  Turtle.cc
