######################################################################
# Automatically generated by qmake (2.00a) Thu Aug 17 14:56:00 2006
######################################################################

CONFIG+=staticlib
TEMPLATE = lib
TARGET = L
DESTDIR = ../lib 
DEPENDPATH += . 
INCLUDEPATH += . ../include ../../c++adt/include

# Input
SOURCES +=  Turtle.cc
