######################################################################
# Automatically generated by qmake (2.00a) Thu Aug 17 14:54:41 2006
######################################################################

CONFIGURE+=staticlib
TEMPLATE = subdirs

# Directories
